### ISSUE TITLE
Bug when updating programmatically a structure field in Kirby if modules plugin activated

### ISSUE THREAD

**Issue by vauvarin** [getkirby-plugins/modules-plugin#11]
Hello,

Sonja and I made many tests to find why my Kirby project bugs. This bug only appear with the modules plugin. We have reproduced the bug on a clean Starterkit install.

In a project, I have a front-end form to collect data and to create a new subpage which contain a structure field.

If the modules plugin AND at least one module are present in the project filesystem, a bug appears when trying to update the structure field. If we remove the module in the /module folder (so /module is empty), the bug disappears.

Bug description:

To create my subpage and structure field, I've followed the documentation you can find here in the Kirby cookbook https://getkirby.com/docs/cookbook/creating-pages-from-frontend

When creating a subpage and structure field programmatically two different txt files are created instead of one:
- one contain the subpage classic fields (title, description ...) > /content/movies/my_title_subpage/movie.txt
- and the other one contain the structure field data. > /content/movies/my_title_subpage/my_title_subpage.txt

This is a link to download a small project built from the starterkit with the minimum of code. You will be able to reproduce the bug by yourself and check the code.

Download it here : http://kirby.confdays.com/movie.zip

I've just added the module plugin and the "text" module from the module plugin démo.

I don't use the module plugin anywhere, it's just present in the filesystem.

When I try to update a structure field, the bug appear (two txt files) if there is a module in the /module folder.

If the /module folder is empty, everything run as expected.

I've added to the starterkit a newmovie page http://localhost/newmovie which display two fields "Title" and "Actor"

When you click the button " Save New Movie" it create a child subpage "Movie"  and add an "Actor" which is a structure text field.

admin user:
log = gilles
psw = yosemite

The code which create the subpage and the structure field is in /site/controllers/newmovie.php

Sorry, this description is a little bit long. Hope it could help you understand the problem.
Thx
Gilles

**Comment by texnixe** [comment]
It's not limited to updating a structure field, it "works" when just updating any fields as well.

**Comment by lukasbestle** [comment]
I will look into this tomorrow.

**Comment by lukasbestle** [comment]
I have tried to reproduce this based on your description but it works just fine for me. Please note that I can't test using your demo site for security reasons and also because I can't easily keep track of the changes you made to the starterkit to be able to debug this properly.

I just did the following:

- Install fresh copy of 2.4.1 starterkit
- Install Modules plugin
- Add `site/modules` directory and add the text module from the demo branch
- Create a module page somewhere (in my case I created `content/home/01-test-module/module.text.txt`)
- Put `$page->update(['Test' => '123']);` into the `project.php` template and call it by accessing a project page

Updating the page works just fine for me. Did I miss something or maybe I didn't understand the issue correctly?
If so, please let me know which steps I need to do to reproduce this. Thanks in advance!

**Comment by texnixe** [comment]
When you just update any page, the issue doesn't occur. As I explained above, it only happens when you create a new page and then try to update it immediately afterwards. This issue does not occur, however, if the modules folder is not present or empty.

**Comment by lukasbestle** [comment]
Ah, interesting. Thanks for the code example.

**Comment by texnixe** [comment]
Addendum: instead of `addToStructure()` you might as well use `page($newRegistration)->update()`. The effect is the same.

**Comment by lukasbestle** [comment]
I can reproduce this now and was able to track it down to [this line](https://github.com/getkirby-plugins/modules-plugin/blob/1.2.0/lib/modules.php#L147). If you comment that out (= don't register the module page model) it all works again.

So this needs to be an issue in the core. However I wasn't able to find the origin of the issue. It seems like the page object you get returned from the page creation is created at a time where the directory exists but the content file doesn't. The result is a page with pretty much all values equal to the UID (title, intendedTemplate etc.). And that's why updating the page writes to the wrong file: The intendedTemplate is wrong.

I have opened an issue at the Kirby repo: https://github.com/getkirby/kirby/issues/528
